FROM python:3.7

RUN pip install bitarray
RUN pip install pandas==1.0.4
RUN pip install scipy==1.2.3
RUN pip install matplotlib==3.1.1
RUN pip install seaborn==0.10.1
RUN pip install jupyterlab
RUN pip install jupyter


#jupyter serverextension enable --py jupyterlab --sys-prefix



